name: Tidy document
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  tidy:
    name: Tidy up
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install tidy-html5
      - run: tidy -ashtml -config build/tidyconfig.txt -o index.html index.html
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "Tidy using tidy-html5"
          commit-message: "Tidy index.html"
          branch: html-tidy